# Generated by Django 2.2.3 on 2019-11-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='название на английском')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='название на японском')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='картинка')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='картинка')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('appeared_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='появился')),
                ('disappeared_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='исчезнет')),
                ('level', models.PositiveIntegerField(blank=True, null=True, verbose_name='уровень')),
                ('health', models.PositiveIntegerField(blank=True, null=True, verbose_name='здоровье')),
                ('strength', models.PositiveIntegerField(blank=True, null=True, verbose_name='сила')),
                ('defence', models.PositiveIntegerField(blank=True, null=True, verbose_name='защита')),
                ('stamina', models.PositiveIntegerField(blank=True, null=True, verbose_name='выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='pokemon_entities.Pokemon', verbose_name='покемон')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='element_types',
            field=models.ManyToManyField(blank=True, null=True, to='pokemon_entities.PokemonElementType', verbose_name='стихия'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolutions', to='pokemon_entities.Pokemon', verbose_name='из кого эволюционировал'),
        ),
    ]
