# Generated by Django 2.2.3 on 2019-11-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20191107_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='pokemons',
            field=models.ManyToManyField(blank=True, null=True, to='pokemon_entities.Pokemon'),
        ),
    ]
