# Generated by Django 2.2.3 on 2019-11-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_pokemonelementtype_pokemons'),
    ]

    operations = [
    ]
